# This file defines SOPS encryption rules for repository secrets.
# The age private key is stored in 1Password and must not be committed.

creation_rules:
  - path_regex: ^talos/talsecret\.sops\.yaml$
    age: age1864739s0808890gcer87xlrpq65messh9dk9j87ku2jgskr2mq7sflhf83

  - path_regex: ^kubernetes/.+\.sops\.ya?ml$
    encrypted_regex: "^(data|stringData)$"
    age: age1864739s0808890gcer87xlrpq65messh9dk9j87ku2jgskr2mq7sflhf83
