# This file defines MinIO credentials materialized from 1Password.

apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: minio-root-credentials
  namespace: minio
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-infra
  target:
    name: minio-root-credentials
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        config.env: |
          export MINIO_ROOT_USER="{{ .username }}"
          export MINIO_ROOT_PASSWORD="{{ .password }}"
  data:
    - secretKey: username
      remoteRef:
        key: "MinIO Root/username"
    - secretKey: password
      remoteRef:
        key: "MinIO Root/password"
