# This file is the root Kustomize entrypoint for Flux bootstrap and synchronization definitions.

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - flux-system
  - platform.yaml
  - apps.yaml
