# This file groups ExternalSecret resources backed by the Infra 1Password vault.

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cloudflare-cert-manager-token.yaml
  - cloudflare-external-dns-token.yaml
