# This file defines baseline namespaces used by platform controllers.

apiVersion: v1
kind: Namespace
metadata:
  name: platform
---
apiVersion: v1
kind: Namespace
metadata:
  name: kube-vip-svc
  labels:
    # kube-vip runs with hostNetwork and NET_ADMIN/NET_RAW capabilities
    # to assign VIPs to physical interfaces and send ARP.
    # https://kube-vip.io/docs/installation/
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/enforce-version: latest
---
apiVersion: v1
kind: Namespace
metadata:
  name: istio-system
---
apiVersion: v1
kind: Namespace
metadata:
  name: external-secrets
---
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
  labels:
    secrets.n4mlz.dev/onepassword-infra: "true"
---
apiVersion: v1
kind: Namespace
metadata:
  name: external-dns
  labels:
    secrets.n4mlz.dev/onepassword-infra: "true"
