# This file aggregates observability configuration resources.

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - collector-rbac.yaml
  - otel-collectors.yaml
  - grafana-datasources.yaml
  - servicemonitors.yaml
  - prometheusrules.yaml
  - istio-telemetry.yaml
