apiVersion: v1
data:
    token: ENC[AES256_GCM,data:WXV6tJOqVnPFrUT1YBWtEI8+7msXIBtRUko48yFHv8qp+RQPKJtizOTk06i5i0apRGBeD38fFst4cI9OiuaM4iTQnjE2qoEVF/42/e81vXxdm0ZEltiiwlv7OMkMpi72AKlRiWCbzoxUU+AMrIlNZ0RwwWAYu7Hz+kD94P0U2hyULXSHbIsT1HsQEN2lWGOqSvu0vylrLPMTAn+MgBCsLs6hkAEGthMUXsyUKmwLuCTHEU6IWN1lp2nNdaff/wQmOVAwdN0PJwK3BLmgv+y4QV6nUM2fkW3NW/2pAsM09/GoUlmX0zYrkAqF72sTet0S/JvxlQ2G2DiiqLIJxglQTmNaH2givyIYD0+6/QQPupERknqNDdYUWdjsyFzv8kcu1vSYaGuZNopK+Hh/yxLTd3qY4m1zuR7PHsMR6zXR8lKjS8JpbBuRFbEe/h4cRLxi6NUeuZREbuiwOxQZRuwe3nUlm0C4dbBBWJilnatvtAB+x5Ntm/IU42fHFdA+NQFt6sFfvR/x+WUFeJq9skoFrqRb+eUKcyCgbOwoc0zFdeQ9CpSoOZNwhCoDgBxh+2Qzl+DyYDBwt2jvpd83gk37PBpX7yNNRXUG1yF4JBLYWV0K0Hvd4+E7Ve1J5BCazZ28a8aZZi4Z9Wc6ZZbkvicRAIQ0dSFNiz7yC55U3Vuutl7+5sAx3plSoHH3IRUsMwyot+SaPTsNewJd3PBlps4Wr86OjR2nGgivce3l50DP0ABkI8a+wNwlPrlp0ojEMpl3Q4mOicQmhNKiVGoVz3rpXMtX6uCceS3p8qQxtWRyxqGkgpUbeRwf4S4Myg+h/ZVzNlU/4K5xjp3vdRn6r9Qca6H0mSO4L2DF1arSLE+eGr/QnklpcXrUGFTeOIkaymfs3bWFZepk8eRr/u9H0zP69nODykSlMgJR9GysjMeue+1EMbFFqCGAsJODe+u+iKAAPYO57tvxQeng2BM/FpYsS3c9UrosHBoK7YssGw0/W9bEpSKUiRqCHvIf29t+dwTqeBmogxrPsY2rvxUPwd4oNyyd0e2m+e8icB6opU1uSaOZlhWU/00+MGPF1Kwcx0nISJdCTIQfEkGGXKuKOaYn5VPaMnxdS4rxv47RkknP26mILfA+ouGWjUhEwz+4S3kZoOj0T32olb3oygvOYW6+03RRwuUk97+N8uokzJg1i2lnTaRLqyeTwPVvGUF96xmgVMGiIobe2VV45hkrs6k3mgw041M6+2j3ldOVIpX0Jnu32m13oaSoQIb3LiW/hj/T4hAvyzESSXPKMa7MahC+vSu2k+KH14D5L3RtkXfB4TwxIPm+4G/PwflYQWvbhT60MMXxGlU+Z/KCUZRmLTwuORNDTsORV9Uo1R3tLOe9t5XF48anr+f7LAlb5iY23wH143NfuFC5D0K5A9gOpIwLtbGxg5+9pl1a7dBOHI0+Og2K5NUf,iv:K91ZogHfy8tO8kcrCI0UUdte4y4GdMrqQS4BYK5D0eQ=,tag:JatNB/dMqkjnsDRYrpRJQQ==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: onepassword-service-account-token
    namespace: platform
sops:
    age:
        - recipient: age1864739s0808890gcer87xlrpq65messh9dk9j87ku2jgskr2mq7sflhf83
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5NmoxaW9VLys1aXNiWTdQ
            bU4zRVVmem0wNUpMZWl5Mjg5ZkwydzloeFMwCjRXaFQrNk5tMWY3VC84NDYrQzlE
            cnU5eHRnWExNaDdxNTl1amlUZ0ZFa00KLS0tIHAzUHEySHI5YUlZVkt4aXBEbDM3
            SXNlcURGMVRhb0Q1Ykk2K2ZTV0c0RFkKvxP1BkjvMr3Lg5NEYyahuK8TgHI4drhA
            dyraRF2SPlst7Y4o434sJCM5KxNxNhMWjtHHXk6sAr8tbzYoBRqQ6Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-06T05:22:37Z"
    mac: ENC[AES256_GCM,data:iqcElWDyJOnQpHKMSPXDCgoqRoglmzB4RPFr2sSo5AbwIDQSnjEC3IwxIH4hEozdDrrZgp+5hemspiwIkjYIAS3BzmWpnui9JYxaYk4401Nz8wlQt1o/xYxWUn7T9lQqI3vUwP7BhiWIu0WAza+aQhhvymxBc/3RSGmxxOTD7qE=,iv:J2TlKim5wdOxK2mqFTVwK85BY9twvqq3jlxdRIk7FUo=,tag:tJUrMfua3l3ET92tXYbSsg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
