# This pool contains public LoadBalancer IPs assigned to Gateway and L4 Services.
# Individual Gateways should request specific addresses from this pool.

apiVersion: cilium.io/v2
kind: CiliumLoadBalancerIPPool
metadata:
  name: public-lb-pool
spec:
  blocks:
    - start: 163.220.236.73
      stop: 163.220.236.76
