# This file aggregates observability backends and controller operators.

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helmrepositories.yaml
  - kube-prometheus-stack.yaml
  - loki.yaml
  - tempo.yaml
  - opentelemetry-operator.yaml
